# Generated by Django 4.0.6 on 2022-09-25 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dm', '0002_canal_canalmensaje_canalusuario_delete_mensaje_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canal',
            old_name='ususarios',
            new_name='usuarios',
        ),
    ]
